services:

  consul:
    image: hashicorp/consul:1.20
    container_name: consul
    ports:
      - "8500:8500"
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 5s
      timeout: 3s
      retries: 5

  catalog-1:
    build: ./catalog_service
    container_name: catalog-1
    environment:
      INSTANCE_NAME: catalog-1
      PORT: 8000
      CONSUL_URL: http://consul:8500
    depends_on:
      consul:
        condition: service_healthy

  catalog-2:
    build: ./catalog_service
    container_name: catalog-2
    environment:
      INSTANCE_NAME: catalog-2
      PORT: 8000
      CONSUL_URL: http://consul:8500
    depends_on:
      consul:
        condition: service_healthy

  auth:
    build: ./auth_service
    container_name: auth
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      CONSUL_URL: http://consul:8500
    depends_on:
      consul:
        condition: service_healthy
  nginx:
    image: nginx:1.27
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - catalog-1
      - catalog-2